### ISSUE TITLE
error while in executing carma_pack setup.py installation

### ISSUE THREAD

**Issue by phanindra1reddy** [brandonckelly/carma_pack#18]
Hi there ,

 I am using CentOS 7, I just followed the steps as contributors explained in Linux_install.text

still I end up with the following..

error: Command "g++ -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/phanindra/anaconda3/include -I/home/phanindra/boost_1_54_0/boost/include -I/home/phanindra/armadillo-9.800.3/include -I/usr/include/ -I./include -I/home/phanindra/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/phanindra/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/phanindra/anaconda3/include/python3.6m -c ./boost_python_wrapper.cpp -o build/temp.linux-x86_64-3.6/boost_python_wrapper.o -O3 -std=c++0x" failed with exit status 1

later I tried running "python testCarmcmc.py" , then displayed as follows

[root@localhost tests]# python testCarmcmc.py
  File "testCarmcmc.py", line 80
    print "Should be using:", np.array(guess)
                           ^
SyntaxError: invalid syntax

any suggestions
thanks and kind regards 
Phanindra

**Comment by brandonckelly** [comment]
Not sure about the build error, there isn't enough information provided. The python error looks to be a python 2 vs 3 issue: make sure you are using python 2.7
