### ISSUE TITLE
cama_process for CAR(1) does not work

### ISSUE THREAD

**Issue by acbecker** [brandonckelly/carma_pack#6]
It looks like the carma_process function does not work with a CARMA(1,0) model due to this line:  

  https://github.com/bckelly80/carma_pack/blob/master/src/carmcmc/carma_pack.py#L1152

This seems to assume that p is 2 or greater.  An "if" statement may be enough to fix this problem, but it would be good to check if there are any more assumptions about the values of p,q (other than q<=p).

**Comment by anetasie** [comment]
Have you made a code to simulate CARMA(1,0) or rather CAR(1) model?

**Comment by brandonckelly** [comment]
No, have not done this yet but will get to it this weekend.

**Comment by brandonckelly** [comment]
I added a function (car1_process) to generate a sample from a CAR(1) process to carma_pack.py.
